# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: vic485's Portfolio
email: victorfuga@gmail.com
name: Victor Fugazzotto
description: >- # this means to ignore newlines until "baseurl:"
  Personal portfolio for Victor Fugazzotto, under the online
  pseudonym of vic485.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vic485.xyz" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: thevic485
github_username:  vic485

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]
